#!/usr/bin/python3
SinglyLinkedList = __import__('100-singly_linked_list').SinglyLinkedList

sll = SinglyLinkedList()
sll.sorted_insert(2)
print(sll)
print("------")
sll.sorted_insert(5)
print(sll)
print("------")
sll.sorted_insert(3)
print(sll)
print("------")
sll.sorted_insert(10)
print(sll)
print("------")
sll.sorted_insert(1)
print(sll)
print("------")
sll.sorted_insert(-4)
print(sll)
print("------")
sll.sorted_insert(-3)
print(sll)
print("------")
sll.sorted_insert(4)
print(sll)
print("------")
sll.sorted_insert(5)
print(sll)
print("------")
sll.sorted_insert(12)
print(sll)
print("------")
sll.sorted_insert(3)
print(sll)
print("------")
print(sll)
